title: Aayush Aryan
# logo: 
# description: text below image
# show_downloads: true
# theme: jekyll-theme-minimal
remote_theme: pages-themes/hacker@v0.2.0
theme: jekyll-remote-theme
# https://pages.github.com/themes/
